build:
  image: armhfbuild/buildpack-deps:jessie-scm
  commands:
    - git clone --single-branch https://github.com/djmaze/docker-mounts upstream
    - sed -i 's/alpine/armhfbuild\/alpine/' upstream/Dockerfile

publish:
  docker:
    context: upstream
    file: upstream/Dockerfile
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: armhfbuild/mounts
